### ISSUE TITLE
Search whole database functionality should separate different fields

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#56] opened 2016-08-19 07:54 UTC
Description: When using whole database search then it finds through different table fields.

Steps required to reproduce the bug:

1.  Click "Search whole database"
2.  Type 31 to the input box
3.  Click button with magnification class

Attach any related screenshots below.
![searchwholedatabase](https://cloud.githubusercontent.com/assets/3479156/17802845/514f48c8-65fb-11e6-93d8-24cf681936b9.jpg)

**Comment by chalkos** [comment] 2016-08-23 11:19
That is the intended behaviour for those cases. But it is not joining fields together.

For example, in the address with id 273 ([this one in the current demo](http://demo.database-preservation.com/#record/233ecc1a-2d06-44a0-abcc-6085105be618/368e443a-314e-4387-b25c-c720f82469c4/917ab8b8-3f51-4441-8578-ca76aa7a5db5)) the value for the column `last_update` is

> Thu Sep 25 22:**31**:21 WEST 2014

and there is a `31` in the minutes part.

--------------

I marked this as a bug because if you would search for `ca76aa7a5db5` you would get one result. that is because that text is part of the record unique identifier (that is only used in the viewer and was not in the original database) and it is being used in the search. and it shouldn't. This issue made me notice that bug while I was looking for the cause of the issue.

**Comment by chalkos** [comment] 2016-08-23 11:23
There is another issue in there. You should have been able to view a shadow on the right side of the table, indicating that there are more columns and that you can scroll to see them.

Could you tell me which browser software you are using and its version?

**Comment by Laurira** [comment] 2016-08-24 07:00
I tried different browsers and the shadow is there. It seems I just missed the scrollbar so I did not notice the last field.

You can close this issue.

**Closed** 2016-08-24 08:07 UTC
Labels: concern: internal, type: bug

**Comment by chalkos** [comment] 2016-08-24 08:15
If you have any suggestions of other ways to hint that the table can be scrolled horizontally, please feel free to suggest them here. The shadow may not be the best visual clue.. . Thanks.
