### ISSUE TITLE
RESTException - after clicking "browse"

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#209] opened 2020-04-23 09:13 UTC
1. Loaded data successfully to DBPTK Desktop
2. Edited some metadata (I am not sure that this is important to mention)
3. Clicked "Browse"
![image](https://user-images.githubusercontent.com/3479156/80081293-6e768280-855b-11ea-893a-a6ff7e394fc3.png)
4. DBVTK logs are empty
5. JVM logs are full of errors:
org.roda.core.data.exceptions.GenericException: Could not convert the database.
	at com.databasepreservation.common.server.controller.SIARDController.convertSIARDtoSolr(SIARDController.java:613) ~[classes!/:2.3.1]
	at com.databasepreservation.common.server.controller.SIARDController.loadFromLocal(SIARDController.java:570) ~[classes!/:2.3.1]
	at com.databasepreservation.common.api.v1.CollectionResource.createCollection(CollectionResource.java:157) [classes!/:2.3.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_242]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) [jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.29.1.jar!/:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.29.1.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.29.1.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.29.1.jar!/:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.29.1.jar!/:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.29.1.jar!/:na]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392) ~[jersey-container-servlet-core-2.29.1.jar!/:na]
	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:385) ~[jersey-container-servlet-core-2.29.1.jar!/:na]
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:560) ~[jersey-container-servlet-core-2.29.1.jar!/:na]
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:501) ~[jersey-container-servlet-core-2.29.1.jar!/:na]
	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:438) ~[jersey-container-servlet-core-2.29.1.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114) ~[spring-boot-actuator-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104) ~[spring-boot-actuator-2.1.9.RELEASE.jar!/:2.1.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.1.10.RELEASE.jar!/:5.1.10.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_242]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.26.jar!/:9.0.26]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Invalid format: "Pealtvaade"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[joda-time-2.10.4.jar!/:2.10.4]
	at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.10.4.jar!/:2.10.4]
	at com.databasepreservation.utils.JodaUtils.xsDatetimeParse(JodaUtils.java:110) ~[dbptk-model-2.6.5.jar!/:na]
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getCell(ToolkitStructure2ViewerStructure.java:706) ~[classes!/:2.3.1]
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getCells(ToolkitStructure2ViewerStructure.java:664) ~[classes!/:2.3.1]
	at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getRow(ToolkitStructure2ViewerStructure.java:650) ~[classes!/:2.3.1]
	at com.databasepreservation.modules.viewer.DbvtkExportModule.handleDataRow(DbvtkExportModule.java:155) ~[classes!/:2.3.1]
	at com.databasepreservation.model.modules.filters.IdentityFilter.handleDataRow(IdentityFilter.java:92) ~[dbptk-model-2.6.5.jar!/:na]
	at com.databasepreservation.model.modules.filters.ObservableFilter.handleDataRow(ObservableFilter.java:123) ~[dbptk-model-2.6.5.jar!/:na]
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.endElement(SIARD2ContentImportStrategy.java:367) ~[dbptk-module-siard-2.6.5.jar!/:na]
	at oracle.xml.parser.v2.XMLMultiHandler.endElement(XMLMultiHandler.java:184) ~[xmlparserv2-12.1.0.2.jar!/:na]
	at oracle.xml.parser.schema.XSDValidator.endElement(XSDValidator.java:894) ~[xmlparserv2-12.1.0.2.jar!/:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseElement(NonValidatingParser.java:1619) ~[xmlparserv2-12.1.0.2.jar!/:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseRootElement(NonValidatingParser.java:448) ~[xmlparserv2-12.1.0.2.jar!/:na]
	at oracle.xml.parser.v2.NonValidatingParser.parseDocument(NonValidatingParser.java:394) ~[xmlparserv2-12.1.0.2.jar!/:na]
	at oracle.xml.parser.v2.XMLParser.parse(XMLParser.java:236) ~[xmlparserv2-12.1.0.2.jar!/:na]
	at com.databasepreservation.modules.siard.in.content.SIARD2ContentImportStrategy.importContent(SIARD2ContentImportStrategy.java:184) ~[dbptk-module-siard-2.6.5.jar!/:na]
	at com.databasepreservation.modules.siard.in.input.SIARDImportDefault.migrateDatabaseTo(SIARDImportDefault.java:60) ~[dbptk-module-siard-2.6.5.jar!/:na]
	at com.databasepreservation.DatabaseMigration.migrate(DatabaseMigration.java:102) ~[dbptk-model-2.6.5.jar!/:2.3.1]
	at com.databasepreservation.common.server.controller.SIARDController.convertSIARDtoSolr(SIARDController.java:606) ~[classes!/:2.3.1]
	... 60 common frames omitted

2020-04-20 09:47:41.013  INFO 22840 --- [o-auto-1-exec-6] o.a.s.u.p.LogUpdateProcessorFactory      : [dbv-activity-logs]  webapp=null path=/update params={}{add=[4cead31f-5f72-4919-ac09-332f3a90f833 (1664473115930918912)]} 0 1

**Comment by luis100** [comment] 2020-04-23 10:44
It seems that the cause is interpreting a cell value as of type datetime and the value being "Pealtvaade" (translation: Top view).

We will probably need the SIARD file to check what is the problem.

```
Caused by: java.lang.IllegalArgumentException: Invalid format: "Pealtvaade"
at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945) ~[joda-time-2.10.4.jar!/:2.10.4]
at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.10.4.jar!/:2.10.4]
at com.databasepreservation.utils.JodaUtils.xsDatetimeParse(JodaUtils.java:110) ~[dbptk-model-2.6.5.jar!/:na]
at com.databasepreservation.common.transformers.ToolkitStructure2ViewerStructure.getCell(ToolkitStructure2ViewerStructure.java:706) ~[classes!/:2.3.1]
```

**Comment by Laurira** [comment] 2020-04-23 11:42
Ok, so data is not perfect. But can I understand from somewhere where this problem is (table and/or column)?

**Comment by Laurira** [comment] 2020-04-24 09:44
I tried to validate it again, the validation failed. I do not understand I have schema2, schema4, schema7 folders under content folder now but in metadata I have schema1, schema2, schema3. Can it be that editing metadata changed folders in the content folder?
Because it validated before. But yes I validated it under windows before and now i validated it again in Linux but it should not matter.
I will try to restore the database in native format and go through the whole process to understand where the issue exactly occurs but as it is 50 GB then in takes time. The native database with licence is in small windows laptop.

**Comment by hmiguim** [comment] 2020-04-24 09:48
Thanks for the report, I'll investigate this issue

**Comment by Laurira** [comment] 2020-04-27 07:13
1. I created the siard again with DBPTK-DESKTOP 2.3.0 (Windows).
2. Then I tried to open the siard or load it into DBPTK-DESKTOP
3. I got an error
![image](https://user-images.githubusercontent.com/3479156/80337580-e77b2000-8862-11ea-9762-61e2d28b510c.png)

**Comment by Laurira** [comment] 2020-04-27 07:15
Tried with latest release of DBPTK-DESKTOP, got slightly different error
![image](https://user-images.githubusercontent.com/3479156/80344279-fd431200-886f-11ea-833e-e479001c8934.png)

**Comment by Laurira** [comment] 2020-04-27 07:18
JVM log: 
[tmp-3012AJAOLYMik836.txt](https://github.com/keeps/db-visualization-toolkit/files/4538058/tmp-3012AJAOLYMik836.txt)

**Comment by Laurira** [comment] 2020-04-28 06:07
DBPTK created siard where metadata.xml has schema1 and schema2 but in the content there is schema2 and schema10

![image](https://user-images.githubusercontent.com/3479156/80452736-8a00d500-892f-11ea-9575-77d03c822381.png)

So I do not understand how did the validation were successful in the January. Maybe validator did not consider the folders of schemas or that version created siard where the folders were correctly named.

**Comment by Laurira** [comment] 2020-04-28 06:48
While validating main error is "P_4.3-1 The structure prescribed in the metadata.xml must be identical to that in the content/ folder."

**Comment by hmiguim** [comment] 2020-05-14 17:59
Close it is an issue related with DBPTK Developer. Mentioned at https://github.com/keeps/db-preservation-toolkit/issues/450

**Closed by hmiguim** 2020-05-14 17:59 UTC
Labels: type: bug
